# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8c92c261720a0b2fddc9c342441261fb74986d566e2f4ea883461998eff3d66be33b485e2752a9d92928622486bbcb05895752b73cd73b45163a40c281d66fe

test:
  secret_key_base: 473186cab981edf516f8b2781f0813ea1c50738345683de393610d43f68b213d5c6560226325701379f01adcde88cb76ad40ee5a811b4485da607521cc0956ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
