users:
  name:
    max_length: 55
  email:
    max_length: 255
  password:
    min_length: 8
  phone_number:
    max_length: 11
  address:
    min_length: 50
    max_length: 255
comments:
  content:
    min_length: 80
products:
  name:
    min_length: 20
per:
  limit_page: 10
order_details:
  quantity:
    default: 1
product:
  name: 
    min_length: 6
  describe: 
    min_length: 6
  picture:
    max_size: 5
uploader:
  picture: 300
